version: '2.4'

services:
  backend:
    image: vk_php_image:latest
    container_name: vk_backend
    expose:
      - 9000
    volumes:
      - .:/var/www/backend/main
      - ${SSH_AUTH_SOCK}:/ssh-agent
    env_file:
      - .env
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    networks:
      - vk

  frontend:
    image: vk_nginx_image:latest
    container_name: vk_frontend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/backend/main
    depends_on:
      - backend
    ports:
      - "8083:80"
    networks:
      - vk

  gearman:
    image: artefactual/gearmand
    container_name: vk_gearman
    expose:
      - 4730
    networks:
      - vk

  workers:
    image: vk_php_image:latest
    container_name: vk_workers
    volumes:
      - .:/var/www/backend/main
      - ./docker/supervisor/group_workers.conf:/etc/supervisor/conf.d/group_workers.conf
    entrypoint: "supervisord -c /etc/supervisor/supervisord.conf -n"
    env_file:
      - .env
    networks:
      - vk

  #mysql:
  #  image: mysql:8.0.21
  #  container_name: mysql_vk
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: vkpass
  #    MYSQL_USER: vkuser
  #    MYSQL_PASSWORD: vkpass
  #    MYSQL_DATABASE: vkdatabase
  #  ports:
  #    - "3316:3306"
  #  healthcheck:
  #    test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #    timeout: 3s
  #    retries: 20
  #  volumes:
  #    - mysql-data:/var/lib/mysql

#volumes:
#  mysql-data:
#    driver: local

networks:
  default:
    external: true
    name: vk

  # общая сеть для всех сервисов vk
  vk:
    name: vk